#!/bin/bash

## JOB NAME
#PBS -N ppdyn_test
## QUEUE NAME
#PBS -q debugq
## COMPUTE RESOURCES REQUESTED FOR THE JOB SELECT = NO. OF CHUNKS/NODES, NCPUS = NO. OF CORES PER CHUNK/NODE
#PBS -l select=1:ncpus=40
## SPECIFY THE EXECUTION TIME LIMIT FOR THE CODE/APPLICATION IN HRS:MINS:SECS FORMAT
#PBS -l walltime=00:30:00
## JOIN THE OUTPUT AND ERROR FILES INTO A SINGLE FILE WITH NAME <JOBNAME>.O<JOBID>
#PBS -j oe
## EXPORT ALL ENVIRONMENT VARIABLES
#PBS -V
#EMAIL IS SENT WHEN THE JOB STARTS, TERMINATES AND ABORTS
#PBS -m bea
## SPECIFY EMAIL ADDRESS FOR NOTIFICATIONS
#PBS -M user.name@domain.org


# LOAD A MODULE BASED ON APPLICATION/CODE REQUIREMENT
module load anaconda/3
conda init
# REMEMBER TO REPLACE user.name WITH YOUR OWN USERNAME
# OR SIMPLY REPLACE THE .BASHRC PATH
source /home/user.name/.bashrc
conda deactivate &>/dev/null
# REMEMBER TO CHANGE IT TO YOUR OWN ENVIRONMENT PATH
# TO FIND THE PATH USE: conda info --envs
conda activate /home/user.name/.conda/envs/ppdyn
module list
export HDF5_USE_FILE_LOCKING='FALSE'

# WORKING DIRECTORY OF CODE/APPLICATION
# ENVIRONMENT VARIABLE FOR ACCESSING THE WORKING DIRECTORY WITH PBS VARIABLE
cd $PBS_O_WORKDIR

# RUN COMMAND BASED ON CODE/APPLICATION
time python ppdyn.py -i input.ini